In [1]:
import pandas as pd
import numpy as np

In [2]:
samm = pd.read_csv('./database/SAMM/samm.csv')
casme = pd.read_csv('./database/CASME/casme.csv')
casme2 = pd.read_csv('./database/CASME2/casme2.csv')

In [3]:
def gatherTime(database, fps):
    for i in range(len(database)):
        if (database.ApexFrame[i] == '/'):
            continue
        diff = (int(database.ApexFrame[i]) - int(database.OnsetFrame[i])) / fps
        if database.Emotion[i] in ['Happiness', 'happiness']:
            emotions['happiness'].append(diff)
        if database.Emotion[i] in ['Fear', 'fear']:
            emotions['fear'].append(diff)
        if database.Emotion[i] in ['Surprise', 'surprise']:
            emotions['surprise'].append(diff)
        if database.Emotion[i] in ['Disgust', 'disgust']:
            emotions['disgust'].append(diff)

In [4]:
emotions = {
    'happiness': [],
    'fear': [],
    'surprise': [],
    'disgust': []
}

In [5]:
gatherTime(casme, 60)
gatherTime(casme2, 200)
gatherTime(samm, 200)

{'happiness': [0.2, 0.4, 0.45, 0.16666666666666666, 0.08333333333333333, 0.16666666666666666, 0.3333333333333333, 0.38333333333333336, 0.3], 'fear': [], 'surprise': [], 'disgust': []}


In [6]:
np.histogram(emotions['happiness'], bins = np.arange(10) / 10)

(array([ 8, 28, 16, 12,  3,  0,  0,  0,  0], dtype=int64),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]))

In [7]:
np.histogram(emotions['fear'], bins = np.arange(10) / 10)

(array([1, 7, 4, 0, 0, 0, 0, 0, 0], dtype=int64),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]))

In [8]:
np.histogram(emotions['surprise'], bins = np.arange(10) / 10)

(array([ 7, 37, 13,  3,  0,  0,  0,  0,  0], dtype=int64),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]))

In [9]:
np.histogram(emotions['disgust'], bins = np.arange(10) / 10)

(array([15, 69, 27,  4,  0,  0,  0,  0,  0], dtype=int64),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]))