In [1]:
import numpy as np
import cv2
import pandas as pd

In [2]:
feature_params = dict(maxCorners = 100,
                       qualityLevel = 0.3,
                       minDistance = 7,
                       blockSize = 7)

In [3]:
lk_params = dict(winSize = (15, 15),
               maxLevel = 2,
               criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 10, 0.03))

In [4]:
color = np.random.randint(0, 255, (100, 3))

In [5]:
old_frame = cv2.imread('./database/CASME2/Cropped/sub01/EP02_01f/reg_img46.jpg')
# old_frame = cv2.resize(old_frame, (250, 160))

In [6]:
old_gray = cv2.cvtColor(old_frame, cv2.COLOR_BGR2GRAY)

p0 = cv2.goodFeaturesToTrack(old_gray, mask = None, **feature_params)

In [7]:
mask = np.zeros_like(old_frame)

In [9]:
for i in range(14):
    frame = cv2.imread('./database/CASME2/Cropped/sub01/EP02_01f/reg_img' + str(i + 47) + '.jpg')
    frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
#     frame_gray = cv2.resize(frame_gray, (250, 160))
    print(frame_gray - old_gray)
    p1, st, err = cv2.calcOpticalFlowPyrLK(old_gray, frame_gray, p0, None, **lk_params)
    
    good_new = p1[st == 1]
    good_old = p0[st == 1]
    
    for j, (new, old) in enumerate(zip(good_new, good_old)):
        a, b = new.ravel()
        c, d = old.ravel()
        mask = cv2.line(mask, (a, b), (c, d), color[j].tolist(), 2)
        frame = cv2.circle(frame, (a, b), 5, color[j].tolist(), -1)
    img = cv2.add(frame, mask)
    
    print(good_new - good_old)
    cv2.imshow('frame', img)
    k = cv2.waitKey(0) 
        
    old_gray = frame_gray.copy()
    p0 = good_new.reshape(-1, 1, 2)
    
cv2.destroyAllWindows()

[[252 253 252 ... 254   4   7]
 [  4   4   1 ... 254   5   7]
 [  7   7   4 ... 255   5   6]
 ...
 [254 254 254 ... 253   3   9]
 [  7 252 248 ... 251 251 254]
 [  7 252 248 ... 251 252 254]]
[[-0.26089478 -0.06200409]
 [-0.23358536 -0.14853668]
 [-0.08618164 -0.07052612]
 [-0.1351471  -0.19493103]
 [-0.1532135  -0.30923462]
 [-0.19683838 -0.3582077 ]
 [-0.1882782  -0.11936188]
 [-0.27956963 -0.09869385]
 [-0.31373596 -0.24517822]
 [-0.23068237 -0.1975174 ]
 [-0.28962708 -0.20178223]
 [-0.07516479 -0.26078796]]
[[  5   3   1 ... 254 255   2]
 [255 254 254 ... 254 254   0]
 [255 254 253 ... 253 252 255]
 ...
 [253 253 255 ... 253 252 252]
 [  1   1   1 ...   1   1 255]
 [  1   1   1 ...   1   0 255]]
[[ 0.00886536 -0.04541016]
 [ 0.02903366  0.00670624]
 [-0.01597595 -0.13322449]
 [-0.03630066  0.00376892]
 [ 0.08048248  0.05426025]
 [-0.06053162 -0.01242828]
 [ 0.00421143  0.04541016]
 [ 0.05389214 -0.03050232]
 [ 0.00364685  0.00369263]
 [ 0.01478577 -0.01847076]
 [-0.02693176 -0.0233

In [35]:
cv2.resize?